language: rust
cache: cargo
before_script:
  - rustup toolchain install nightly
  - rustup default nightly
  - rustup component add rustfmt-preview
  - rustup default stable
script:
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
