language: rust
before_script:
  - rustup toolchain install nightly
  - rustup run nightly rustup component add rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly
script:
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
